version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
      - image: redis
    working_directory: ~/github.com/gopherpun/redis_queue
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run: 
        name: Wait for Redis
        command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run: go test -race


